name: Release

on:
  push:
    branches:
      - main
    tags:
      - "!**"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write # required for git operations
      id-token: write # required for OIDC
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # git history to generate changelog

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24 # OIDC requires npm v11.5.1 or later
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Format Check
        run: npm run fmt:check

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
